##comment
---
app: amundsen-development
auto_deploy: true
context: release-handsup-us-east-1
domain: amemsenennn.releaseapp.gethandsup.com
mode: development
repo_name: dustyspace/amundsen
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1200m
    requests: 100m
  memory:
    limits: 1200Mi
    requests: 100Mi
  replicas: 1
hostnames:
- frontend: frontend-${env_id}-${domain}
services:
- name: postgres
  image: postgres:11
- name: redis
  image: redis
- name: backend
  image: dustyspace/amundsen/nginx
  has_repo: true
- name: vote
  image: dustyspace/amundsen/vote
  has_repo: true
charts:
- name: amundsen
  directory: amundsen-kube-helm/templates/helm
  values: values.yaml
- name: ingress
  directory: amundsen-kube-helm/templates/release-ingress
  values: values.yaml
- name: remote-ingress
  repo_url: https://github.com/releasehub-com/helm-ingress.git
  directory: amundsen-kube-helm/templates/release-ingress
  values: values.yaml
- name: vault
  repo_url: https://helm.releases.hashicorp.com
  add: hashicorp
  install: hashicorp/vault
  directory: helm/hashicorp
  values: values.yml
infrastructure:
- name: make-s3-bucket
  type: terraform
  directory: terraform
  values: values.yaml
builds:
- name: nginx
  dockerfile: Dockerfile.release
- namme: vote
  repo_url: https://github.com/dustyspace/example-vote-1.git
  context: vote
jobs:
- name: migrate
  command:
  - sh
  - "-c"
  - sleep 5
  from_services: backend
  halt_on_error: true
workflows:
- name: setup
  parallelize:
  - step: amundsen
    tasks:
    - charts.amundsen
    - charts.ingress
    - charts.remote-ingress
- name: patch
  parallelize:
  - step: amundsen-stepz
    tasks:
    - charts.amundsen
- name: teardown
  parallelize:
  - step: amundsen-teardown
    tasks:
    - charts.amundsen
  - step: release-teardown
    tasks:
    - release.remove_environment

