##comment
---
app: amundsen-development
auto_deploy: true
context: release-handsup-us-east-1
domain: amundsen.releaseapp.gethandsup.com
mode: development
repo_name: dustyspace/amundsen
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 123m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
hostnames:
- frontend: frontend-${env_id}-${domain}
services:
- name: postgres
  image: postgres:11
- name: redis
  image: redis
  command: ['sh', '-c', "echo 'failing now...' && sleep 5 && exit 1"]
- name: backend
  image: dustyspace/amundsen/nginx
  has_repo: true
charts:
- name: amundsen
  directory: amundsen-kube-helm/templates/helm
  values: values.yaml
- name: ingress
  directory: amundsen-kube-helm/templates/release-ingress
  values: values.yaml
builds:
- name: nginx
  dockerfile: Dockerfile.release
jobs:
- name: migrate
  command:
  - sh
  - "-c"
  - "echo 'failing now...' && sleep 5 && exit 1"
  from_services: backend
workflows:
- name: setup
  parallelize:
  - step: redis
    tasks:
    - services.redis
    wait_for_finish: false
    halt_on_error: true
  - step: data
    tasks:
    - services.postgres
    - services.redis
  - step: amundsen
    tasks:
    - charts.amundsen
    - charts.ingress
- name: patch
  parallelize:
  - step: amundsen-stepz
    tasks:
    - charts.amundsen

