---
gitops:
  immutable_keys: ['CUSTOMER_NAME']
defaults:
- key: CUSTOMER_NAME
  value:
- key: OTHER_VAR
  value: where are you?
- key: ONE_MORE_ENV
  value: from fresh-branch branch updated
- key: POSTGRES_HOST_AUTH_METHOD
  value: trust
- key: TEST_ENV
  value: true
- key: TESTER
  value: not ok
services: {}

