---
gitops:
  immutable_keys: ['CUSTOMER_NAME']
defaults:
- key: CUSTOMER_NAME
  value:
- key: NEW_ENV_VAR
  value: are you going to make it?
- key: OTHER_VAR
  value: where are you?
- key: ONE_MORE_ENV
  value: from fresh-branch branch
- key: POSTGRES_HOST_AUTH_METHOD
  value: trust
- key: TEST_ENV
  value: true
services: {}

