---
gitops:
  immutable_keys: ['CUSTOMER_NAME']
# comment
defaults:
- key: CUSTOMER_NAME
  value:
- key: NOTHER_VAR
  value: err you are you?
- key: ANOTHER_VAR
  value: where are you?
- key: OTHER_VAR
  value: where are you?
- key: ONE_MORE_ENV
  value: from test-gitops branch
- key: POSTGRES_HOST_AUTH_METHOD
  value: trust
- key: TEST_ENV
  value: true
services: {}

