---
gitops:
  immutable_keys: ['CUSTOMER_NAME']
defaults:
- key: CUSTOMER_NAME
  value:
- key: OTHER_VAR
  value: savage
- key: POSTGRES_HOST_AUTH_METHOD
  value: trust
- key: TEST_ENV
  value: true
services: {}

