---
gitops:
  immutable_keys: ['CUSTOMER_NAME']
defaults:
- key: CUSTOMER_NAME
  value: main-branch-customer-xxx-yyy-zzz-000-111-222-333-444-555-666-777-888
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO_ALSO_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT
  value: 
- key: POSTGRES_HOST_AUTH_METHOD
  value: trust
- key: TEST_ENV
  value: true
- key: ANOTHER_ENV_VAR
  value: this is the value
- key: YES
  value: yes
services: {}

