---
gitops:
  immutable_keys: ['CUSTOMER_NAME']
defaults:
- key: CUSTOMER_NAME
  value: main-branch-customers
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO_ALSO_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT_ALSO_ALSO
  value: 
- key: RELEASE_RANDOM_TEST_IT
  value: 
- key: POSTGRES_HOST_AUTH_METHOD
  value: trust
- key: TEST_ENV
  value: true
services: {}

